[package]
name = "split"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
web-sys = { version = "0.3.60", features = ["console"] }
wasm-bindgen = "0.2.83"
glam = "0.22"
index_vec = "0.1.3"
itertools = "0.10"
